SELECT DISTINCT ?uri ?name (COUNT(DISTINCT ?pub) as ?total)
WHERE {
    VALUES ?dtuOrg { ?org }
    ?dtuOrg a tmp:Dtu ;
            tmp:relates ?pub .
    ?uri a tmp:External ;
            tmp:name ?name ;
            tmp:relates ?pub
}
GROUP BY ?uri ?name
ORDER BY DESC(?total) ?name
