#!/bin/sh

if [ `id -u` -gt 0 ]
then
     echo "please use: sudo ./deploy" >&2
     exit 1
fi
export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
/etc/init.d/tomcat8 stop
cd custom-vivo
if [ ! -d webapp/src/main/webapp/WEB-INF/resources ]
then
    mkdir --parents webapp/src/main/webapp/WEB-INF/resources
fi
cp build.properties webapp/src/main/webapp/WEB-INF/resources/build.properties
mvn $* -Dhttps.protocols=TLSv1.2 install -s settings.xml
/etc/init.d/tomcat8 start
exit 0
