#!/bin/sh

if [ `id -u` -gt 0 ]
then
     echo "please use: sudo ./build.sh" >&2
     exit 1
fi
export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
/etc/init.d/tomcat8 stop
cd custom-vivo
mvn install -s settings.xml
/etc/init.d/tomcat8 start
exit 0
