SELECT ?subOrgName (group_concat(distinct ?auName ; separator = ";") as ?authors)
WHERE {
    ?p a wos:Publication ;
        tmp:relates ?so .
    ?so a tmp:DtuSubOrg ;
        tmp:name ?subOrgName .
  OPTIONAL {
    ?p tmp:relates ?au .
    ?au a tmp:Authorship ;
        tmp:name ?auName ;
        tmp:relates ?so .
  }
}
GROUP BY ?subOrgName
ORDER BY ?subOrgName
