CONSTRUCT {
    ?org a wos:SubOrganization ;
        rdfs:label ?dtuSubOrgName ;
        vivo:relatedBy ?address .
    ?address a wos:Address ;
        vivo:relates ?pub .
    ?authorship a vivo:Authorship ;
            wos:fullName ?name ;
            vivo:relates ?pub, ?address .
    ?pub a wos:Publication .
}
WHERE {
  {
    ?org a wos:SubOrganization ;
        rdfs:label ?dtuSubOrgName ;
        vivo:relatedBy ?address .
    ?address a wos:Address ;
        vivo:relates ?pub .
    ?authorship a vivo:Authorship ;
            wos:fullName ?name ;
            vivo:relates ?pub, ?address .
    ?pub a wos:Publication .
  } UNION {
    ?org a wos:SubOrganization ;
        rdfs:label ?dtuSubOrgName ;
        vivo:relatedBy ?address .
    ?address a wos:Address ;
        vivo:relates ?pub .
    ?pub a wos:Publication .
  }
 }
